name: Deploy to VPS

on:
  push:
    branches:
      - main  # Trigger the action when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Use the Python version you want (e.g., 3.9)

    - name: Set up virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt  # Make sure your requirements file is up to date

    - name: SSH into VPS and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}  # Store your private key in GitHub secrets
        VPS_HOST: ${{ secrets.VPS_HOST }}  # Store your VPS host address in GitHub secrets
        VPS_USER: ${{ secrets.VPS_USER }}  # Store your VPS user in GitHub secrets
      run: |
        # SSH into the server and deploy
        ssh -i $SSH_PRIVATE_KEY $VPS_USER@$VPS_HOST << 'EOF'
          cd /home/qri/paper/research-papers  # Navigate to your app directory
          git pull origin main  # Pull the latest changes
          source venv/bin/activate  # Activate the virtual environment
          pip install -r requirements.txt  # Install/update dependencies
          pm2 restart python3  # Restart the PM2 process (use your PM2 app name)
        EOF
